### ISSUE TITLE
Merge Master to GH pages

### ISSUE THREAD

**Issue by LudeeD** [bnan/dhroraryus#18]
I added the timetable of the MIECT 2nd year so that it could be imported
Can't issue a merge request to merge to gh pages so it would be accessible in the demo page.

**Comment by pkill37** [comment]
The `gh-pages` branch is not meant to be touched directly, you run `npm run deploy` when you want to deploy. Alternatively we could setup automatic CI/CD.

Anyway I've deployed the changes. 😄

**Comment by LudeeD** [comment]
Always a pleasure see you work
