### ISSUE TITLE
Issues displaying Preferences value properly 

### ISSUE THREAD

**Issue by josepduarte** [bnan/dhroraryus#6]
![prefereces](https://user-images.githubusercontent.com/15365800/30330489-25c9dab0-97cd-11e7-8c64-e9801626e34f.jpg)
![preferences2](https://user-images.githubusercontent.com/15365800/30330766-df14239a-97cd-11e7-9e23-a8ff77d4d0a7.jpg)

**Comment by josepduarte** [comment]
It happens to me, I don't know why. Screen resolution?

**Comment by pkill37** [comment]
The select dropdown will be replaced eventually, I'm not satisfied with it. It was just quicker for the purposes of the hackathon.

Before I look for a nicer UI, I just want to make sure that the algorithm will continue to be fed integer scores in the range 0-10. What do you think?

**Comment by josepduarte** [comment]
I think the range has to be at least superior than the number of heuristics, in order to be possible to order all somehow. I think 10 it's a good range for now but it will always depend on the number of heuristics.

Another important thing is that we have to search/investigate a little bit more in how to make all preferences fair.  We opted to just multiply the ones which return a small "percentage/preference" by a constant but that does not guarantee that schedules are ordered properly.
For example, a schedule with a high number of free days returns something like '0,4' (corresponding to two free days), while a "not that contiguous" schedule can return things like 0,6 or higher. Multiplying small ones can make it better but I don't think it's a "fair" solution still. 

I will look into a better way to handle this.

**Comment by pkill37** [comment]
Fixed in #16 somewhat
